### ISSUE TITLE
Can't use multiple tabs in the same Binary Ninja window

### ISSUE THREAD

**Issue by austin-ralls-cs** [CarveSystems/banjo#14]
If you open multiple Dex files in different tabs in the same window, you will get bad behavior and wrong results.

https://github.com/CarveSystems/banjo/blob/bd07db6c3a8de9b4eff56d381c581909b0ea2b05/architecture.py#L44-L58

**Comment by negasora** [comment]
Might be solvable by ui context notifications? https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/ui_notifications.py
