### ISSUE TITLE
numbers don't behave well in binja

### ISSUE THREAD

**Issue by austin-ralls-cs** [CarveSystems/banjo#28]
Trying to change them from one format to another breaks them completely. I suspect that this has something to do with IntegerToken, which used to be marked as internal-only in the docs but isn't any more.

TODO investigate changes to https://api.binary.ninja/binaryninja.function.InstructionTextToken.html#binaryninja.function.InstructionTextToken to figure out how to fix this.

**Comment by ElykDeer** [comment]
You need to populate the `value` field of integer tokens.
